#document settings
title: Testing Prose.io based editing
description: "Testing Prose.io based editing"
url: http://daveloyall.github.io/
repo_name: daveloyall.github.io
branch: master

#global settings, no need to change these
root_url: http://daveloyall.github.io
org_name: daveloyall
prose_url: http://daveloyall.github.io/contribute/

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
